site_name: Dreaming about robot wife
site_url: https://xiong-jie-y.github.io/robo-yome/
nav:
  - Blogging:
      - 3D Reconstruction:
        - 3d_reconstruction/01_survey_3d_reconstruction.md
      - Dataset:
        - dataset/01_instance_segmentation_annotation.md
  - Profile: 
      - my_profile.md
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: light blue
    accent: light blue
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/xiong-jie-y
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_xiongjie_
  disqus: robo-yome
  manifest: manifest.webmanifest
google_analytics:
  - G-MXP088YF0G
  - auto
markdown_extensions:
  - footnotes
  - mdx_truly_sane_lists:
      nested_indent: 2
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML